### ISSUE TITLE
Incompatible with rest-client 2.0

### ISSUE THREAD

**Issue by amatriain** [crohr/rest-client-components#13]
When trying to use rest-client-components with rest-client 2.0, an error is raised:

``` ruby
>> u = 'http://google.com'
"http://google.com"
>> RestClient.get u
NoMethodError: undefined method `redirection_history' for {}:Hash
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:20:in `history'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:39:in `response_set_vars'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/response.rb:44:in `create'
    from /home/amatriain/git/rest-client-components/lib/restclient/components.rb:18:in `call'
    from /home/amatriain/git/rest-client-components/lib/restclient/components.rb:139:in `execute'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:207:in `_follow_redirection'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:119:in `follow_redirection'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:95:in `return!'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:860:in `process_result'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:776:in `block in transmit'
    from /home/amatriain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:766:in `transmit'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
    from /home/amatriain/git/rest-client-components/lib/restclient/components.rb:206:in `block in <module:RestClient>'
    from /home/amatriain/git/rest-client-components/lib/restclient/components.rb:12:in `call'
    from /home/amatriain/git/rest-client-components/lib/restclient/components.rb:139:in `execute'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
    from /home/amatriain/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient.rb:67:in `get'
```

The same error is raised in some specs.

This is probably caused because RestClient 2.0 has added a `RestClient::Response#history` method to keep track of a redirections chain (see https://github.com/rest-client/rest-client#redirection and https://github.com/rest-client/rest-client/commit/5e5fcd95808c288118a7b28d5e25a44ec709c62f). Rest-client-components is not compatible with this change, and is passing a Hash object to rest-client which does not implement the `history` method.

**Comment by JasonLunn** [comment]
👍
